version: "3.8"
services:

    # PHP service
    app:
        build:
            context: .
            dockerfile: php/Dockerfile
        container_name: php-app
        ports:
            - 80:80        
        networks:
            - app-network
        volumes:
            - ./php:/var/www/html
            - ./php/entrypoint.sh:/entrypoint.sh
        env_file:
            - ./.env

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network
        volumes:
            - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
    app-network:
        driver: bridge
